---
title: "Week 4, Day 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library(janitor)

# As you can see, I have included my version of the `read_enrollment()`
# function. Take a look! Is it similar to yours? Where does it differ? Note that
# I have added a check at the beginning. skip_lines should always be a numer. If
# it isn't, something is wrong and I should investigate was it is going on. I
# have also restructured the function so that, instead of just being a pipe that
# vomits out whatever tibble emerges from it, we create an object and then test
# that that object passes a basic sniff test.

# We I expect this level of care in your final project? No! But if you really
# want to ensure that your code works, the only way is to test it. Professional
# data analysts spend a surprising amount of their time testing.

# The cost of not using the just-spit-out-the-pipe strategy is that we need to
# explicitly return the object we want at the end of the function.

read_enrollment <- function(file, skip_lines = 3){
  
  stopifnot(is.numeric(skip_lines))
  
  x <- read_excel(file, skip = skip_lines) %>% 
        clean_names() %>% 
        filter(! is.na(course_title)) %>% 
        select( -instructor_full_name, -course_section_code, -(grad:total)) %>%
        rename_with(~ str_replace(.x, "course_", "")) %>% 
        group_by(id, title, name, department) %>% 
        summarize(u_grad = sum(u_grad), .groups = "drop") %>% 
        filter(u_grad > 10)

  stopifnot(nrow(x) > 100)
  
  return(x)
}
```

Let's continue working with the same enrollment data as Tuesday.  Recall the [official source](https://registrar.fas.harvard.edu/faculty-staff/courses/enrollment/archived-course-enrollment-reports).

### Scene 1

**Prompt:** Create a tibble named `classes` which includes the data from all five years in a "tidy" format. In addition to the variables produced by `read_enrollemnt()`, your tibble should include a variable named `year`.



### Scene 2

**Prompt:** Write a function called `big_classes()` whose first argument `x` requires a tibble, formatted like `classes`. It should return a tibble with the 5 highest enrollment classes in `x`. Once everyone in your group has that working, add a function argument called `my_year` which allows the user to pick a year for which she wants to know the biggest 5 courses.




### Scene 3

**Prompt:** Chapter 4 explains list-columns and the map_* family of functions. Use those tools to create a pipe for each sub-part below which accomplishes the specified task. I recommend you consult the chapter as you get started.

* Create a tibble with a row for each year which includes a list-column named `q_enrollment` in which is stored the results of running `quantile()` on enrollment.



* You now have a tibble with two columns: `year` and `q_enrollment`. Add another column called `mean_25_75` which is the average of the 25th and 75th percentiles. (You should look at `?quantile` to determine which elements in the list these are.) 




### Scene 4

**Prompt:** The current version of the chapter does not mention `group_nest()`, which is a brand new function in **dplyr** package. Examine it by typing `?group_nest`. Read the help page. Play with the examples.  Note how `group_nest()` creates a new tibble with just the grouping variable and a new column, called `data` which is a list-column containing a tibble of all the relevant data. This is confusing, but powerful. Using `classes`, make a new tibble, named `plots` which has three columns: `year`, `data` and `my_plot`. 

Each row in `my_plot` should be a histogram of the enrollment data for that year. Once you have created the object `plots`. Use `plot_grid()` from the **cowplot** package --- which you probably need to install --- to print out all the plots at once.




### Scene 5

**Prompt:** Make an interesting plot with this data. Take that plot and publish it on Rpubs. Add a link to the Rpubs in the #general Slack channel.

